// Code generated by protoc-gen-go. DO NOT EDIT.
// source: processor.proto

package processor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CPU struct {
	Brand                string   `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cores                uint32   `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
	Threads              uint32   `protobuf:"varint,4,opt,name=threads,proto3" json:"threads,omitempty"`
	MinGhz               float64  `protobuf:"fixed64,5,opt,name=min_ghz,json=minGhz,proto3" json:"min_ghz,omitempty"`
	MaxGhz               float64  `protobuf:"fixed64,6,opt,name=max_ghz,json=maxGhz,proto3" json:"max_ghz,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CPU) Reset()         { *m = CPU{} }
func (m *CPU) String() string { return proto.CompactTextString(m) }
func (*CPU) ProtoMessage()    {}
func (*CPU) Descriptor() ([]byte, []int) {
	return fileDescriptor_6783724e039e1aa6, []int{0}
}

func (m *CPU) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CPU.Unmarshal(m, b)
}
func (m *CPU) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CPU.Marshal(b, m, deterministic)
}
func (m *CPU) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CPU.Merge(m, src)
}
func (m *CPU) XXX_Size() int {
	return xxx_messageInfo_CPU.Size(m)
}
func (m *CPU) XXX_DiscardUnknown() {
	xxx_messageInfo_CPU.DiscardUnknown(m)
}

var xxx_messageInfo_CPU proto.InternalMessageInfo

func (m *CPU) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *CPU) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CPU) GetCores() uint32 {
	if m != nil {
		return m.Cores
	}
	return 0
}

func (m *CPU) GetThreads() uint32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *CPU) GetMinGhz() float64 {
	if m != nil {
		return m.MinGhz
	}
	return 0
}

func (m *CPU) GetMaxGhz() float64 {
	if m != nil {
		return m.MaxGhz
	}
	return 0
}

func init() {
	proto.RegisterType((*CPU)(nil), "CPU")
}

func init() {
	proto.RegisterFile("processor.proto", fileDescriptor_6783724e039e1aa6)
}

var fileDescriptor_6783724e039e1aa6 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x4f,
	0x4e, 0x2d, 0x2e, 0xce, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x9a, 0xc8, 0xc8, 0xc5,
	0xec, 0x1c, 0x10, 0x2a, 0x24, 0xc2, 0xc5, 0x9a, 0x54, 0x94, 0x98, 0x97, 0x22, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0xe1, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x81,
	0x05, 0xc1, 0x6c, 0x90, 0xca, 0xe4, 0xfc, 0xa2, 0xd4, 0x62, 0x09, 0x66, 0x05, 0x46, 0x0d, 0xde,
	0x20, 0x08, 0x47, 0x48, 0x82, 0x8b, 0xbd, 0x24, 0xa3, 0x28, 0x35, 0x31, 0xa5, 0x58, 0x82, 0x05,
	0x2c, 0x0e, 0xe3, 0x0a, 0x89, 0x73, 0xb1, 0xe7, 0x66, 0xe6, 0xc5, 0xa7, 0x67, 0x54, 0x49, 0xb0,
	0x2a, 0x30, 0x6a, 0x30, 0x06, 0xb1, 0xe5, 0x66, 0xe6, 0xb9, 0x67, 0x54, 0x81, 0x25, 0x12, 0x2b,
	0xc0, 0x12, 0x6c, 0x50, 0x89, 0xc4, 0x0a, 0xf7, 0x8c, 0xaa, 0x24, 0x36, 0xb0, 0xd3, 0x8c, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x0b, 0x46, 0x66, 0xad, 0x00, 0x00, 0x00,
}
